#!/bin/bash

# Configure Colours
BLUE_COLOUR='\e[36m'
WHITE_COLOUR='\e[0m'

# Set script echo header
HEADER="[${BLUE_COLOUR}AUTO KBL${WHITE_COLOUR}]"

log()
{
	read -t 0.01 MESSAGE
	echo -e "$HEADER $MESSAGE" #| tee -a ~/.temp/autoKBL
}

if [ ! -f ~/.temp/autoKBL ]; then
	touch ~/.temp/autoKBL
	echo "$(date '+%F_%H:%M:%S')" >> ~/.temp/autoKBL
else
	echo "$(date '+%F_%H:%M:%S')" >> ~/.temp/autoKBL
fi

if [ ! -f ~/.config/autoKBL.list ];then
	echo -e "Config file '~/.config/autoKBL.list' is missing." | tee -a ~/.temp/autoKBL | log
	exit 1
else
	if [ $(wc -l ~/.config/autoKBL.list | cut -d ' ' -f 1 ) -eq "0" ]; then
		log "Config file empty."
		exit 1
	else
		mapfile -t listFile < ~/.config/autoKBL.list
	fi
fi

DEVICE_COUNT=0

for line in "${listFile[@]}"; do

	LAYOUT=$(echo ${line} | cut -d '|' -f 1)
	KEYBOARD_NAME=$(echo ${line} | cut -d '|' -f 2)

	# Find the device ID of the keyboard
	DEVICE_ID=$(xinput list --id-only "keyboard:""$KEYBOARD_NAME" 2>>~/.temp/autoKBL)

	# Check if a device ID was found
	if [ ! -z "$DEVICE_ID" ]; then
		echo -e "$KEYBOARD_NAME detected with device ID $DEVICE_ID." >> ~/.temp/autoKBL

		# Increment 
		((DEVICE_COUNT++))
		# Set the keyboard layout
		setxkbmap -device "$DEVICE_ID" -layout "$LAYOUT"

		if [ $? -eq 0 ]; then
			echo -e "$KEYBOARD_NAME (id=$DEVICE_ID) layout set to $LAYOUT." | tee -a ~/.temp/autoKBL | log
		else
			echo -e "Failed to modify keyboard layout for $KEYBOARD_NAME." | tee -a ~/.temp/autoKBL | log

			exit 1
		fi
	fi
done

if [ "$DEVICE_COUNT" -eq "0" ];then
	echo -e "No configured devices detected." | tee -a ~/.temp/autoKBL | log
else
	echo -e "$DEVICE_COUNT device(s) setup." | tee -a ~/.temp/autoKBL | log
fi
